### ISSUE TITLE
(define x (c-value 'int32 42)) fails to print

### ISSUE THREAD

**Issue by rebcabin** [JeffBezanson/femtolisp#56] opened 2019-06-06 17:01 UTC
I believe the fix is just to change line 100 of print.c to say

        assert(iscvalue(v) || iscprim(v));

instead of 

        assert(iscvalue(v));

**Comment by JeffBezanson** [comment] 2019-06-06 17:12
Looks like a duplicate of #53.

**Closed by JeffBezanson** 2019-06-06 17:12 UTC

**Comment by rebcabin** [comment] 2019-06-06 23:57
roger that :)
